FROM node:20.5.0-alpine3.18 as build-stage
ARG API_URL
ENV API_URL=$API_URL
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN ["npm", "run", "build"]
#CMD ["npm", "start"]

#nginx
FROM nginx:1.25.1-alpine3.17-slim
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "g", "daemon off;"]






