FROM node:20.5.0-alpine3.18 as build-stage
ARG API_URL
ENV API_URL=$API_URL
WORKDIR /app/
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000
#RUN npm run build
CMD ["npm", "start"]

#nginx
#FROM nginx:alpine
#RUN rm /etc/nginx/conf.d/default.conf
#RUN rm -rf /usr/share/nginx/html/index.html*
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY --from=build-stage /app/.nuxt/dist /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]